src/MyUCommerceApp.Website/Models/AddressDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyUCommerceApp.Website.Models
{
	public class AddressDetailsViewModel
	{
		public AddressDetailsViewModel()
		{
			ShippingAddress = new AddressViewModel();
			BillingAddress = new AddressViewModel();
			AvailableCountries = new List<SelectListItem>();
		}
		public AddressViewModel ShippingAddress { get; set; }

		public AddressViewModel BillingAddress { get; set; }

		public IList<SelectListItem> AvailableCountries { get; set; }
	}
}

src/MyUCommerceApp.Website/Models/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyUCommerceApp.Website.Models
{
	public class CategoryViewModel
	{
		public CategoryViewModel()
		{
			Categories = new List<CategoryViewModel>();
			Products = new List<ProductViewModel>();
		}
		public string Url { get; set; }

		public string Name { get; set; }

		public string Description { get; set; }

		public IList<CategoryViewModel> Categories { get; set; }

		public IList<ProductViewModel> Products { get; set; } 
	}
}

src/MyUCommerceApp.Website/Models/PaymentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyUCommerceApp.Website.Models
{
	public class PaymentViewModel
	{
		public PaymentViewModel()
		{
			AvailablePaymentMethods = new List<SelectListItem>();	
		}

		public IList<SelectListItem> AvailablePaymentMethods { get; set; }

		public int SelectedPaymentMethodId { get; set; }
	}
}

src/MyUCommerceApp.Website/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using UCommerce.Api;

namespace MyUCommerceApp.Website.Models
{
	public class ProductViewModel
	{
		public ProductViewModel()
		{
			Variants = new List<ProductViewModel>();
		}
		public bool IsVariant { get; set; }

		public string Name { get; set; }

		public string Url { get; set; }

		public string LongDescription { get; set; }

		public IList<ProductViewModel> Variants { get; set; }

		public string Sku { get; set; }

		public string VariantSku { get; set; }

		public PriceCalculation PriceCalculation { get; set; }
	}
}

src/MyUCommerceApp.Website/Models/ShippingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyUCommerceApp.Website.Models
{
	public class ShippingViewModel
	{
		public ShippingViewModel()
		{
			AvailableShippingMethods = new List<SelectListItem>();
		}
		public IList<SelectListItem> AvailableShippingMethods { get; set; }

		public int SelectedShippingMethodId { get; set; }
	}
}

src/MyUCommerceApp.Website/Controllers/MasterClassPartialViewController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using MyUCommerceApp.Website.Models;

namespace MyUCommerceApp.Website.Controllers
{
	public class MasterClassPartialViewController : Umbraco.Web.Mvc.SurfaceController
    {
        public ActionResult CategoryNavigation()
        {
            var categoryNavigation = new CategoryNavigationViewModel();

            return View("/views/mc/PartialViews/CategoryNavigation.cshtml", categoryNavigation);
        }

        private IList<CategoryViewModel> MapCategories(ICollection<UCommerce.EntitiesV2.Category> categoriesToMap)
        {
            var categoriesToReturn = new List<CategoryViewModel>();

            return categoriesToReturn;
        }
    }
}

src/MyUCommerceApp.Website/Views/mc/AddressDetails.cshtml
@using System.Web.Mvc.Html
@using MyUCommerceApp.Website.Models
@model MyUCommerceApp.Website.Models.AddressDetailsViewModel
@{
    Layout = "Layout.cshtml";
}

<form method="POST">
    <div class="row-fluid">
        <div class="well span6">
            <legend>Billing</legend>
            <div class="span12">
                <div class="span5 control-group">
                    <label>First name</label>
                    @Html.TextBoxFor(x => x.BillingAddress.FirstName, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="col-lg-2 control-label">Last name</label>
                    @Html.TextBoxFor(x => x.BillingAddress.LastName, new { @class = "span12" })
                </div>
            </div>
            <div class="span12">
                <div class="span5 control-group">
                    <label>E-mail</label>
                    @Html.TextBoxFor(x => x.BillingAddress.EmailAddress, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="">Company</label>
                    @Html.TextBoxFor(x => x.BillingAddress.CompanyName, new { @class = "span12" })
                </div>
            </div>
            <div class="span12">
                <div class="span5 control-group">
                    <label class="">Attention</label>
                    @Html.TextBoxFor(x => x.BillingAddress.Attention, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="">Line 1</label>
                    @Html.TextBoxFor(x => x.BillingAddress.Line1, new { @class = "span12" })
                </div>
            </div>
            <div class="span12">
                <div class="span5 control-group">
                    <label class="">Line 2</label>
                    @Html.TextBoxFor(x => x.BillingAddress.Line2, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="">City</label>
                    @Html.TextBoxFor(x => x.BillingAddress.City, new { @class = "span12" })
                </div>
            </div>
            <div class="span12">
                <div class="span5 control-group">
                    <label class="">Postal code</label>
                    @Html.TextBoxFor(x => x.BillingAddress.PostalCode, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="">Country</label>
                    @Html.DropDownList("BillingAddress.CountryId", Model.AvailableCountries, new { @class = "span12" })
                </div>
            </div>
            <div class="span12">
                <div class="span5 control-group">
                    <label class="">Phone</label>
                    @Html.TextBoxFor(x => x.BillingAddress.PhoneNumber, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="">Mobile phone</label>
                    @Html.TextBoxFor(x => x.BillingAddress.MobilePhoneNumber, new { @class = "span12" })
                </div>
            </div>
        </div>
    
        <div class="well span6">
            <legend>Shipping</legend>
            <div class="span12">
                <div class="span5 control-group">
                    <label>First name</label>
                    @Html.TextBoxFor(x => x.ShippingAddress.FirstName, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="col-lg-2 control-label">Last name</label>
                    @Html.TextBoxFor(x => x.ShippingAddress.LastName, new { @class = "span12" })
                </div>
            </div>
            <div class="span12">
                <div class="span5 control-group">
                    <label>E-mail</label>
                    @Html.TextBoxFor(x => x.ShippingAddress.EmailAddress, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="">Company</label>
                    @Html.TextBoxFor(x => x.ShippingAddress.CompanyName, new { @class = "span12" })
                </div>
            </div>
            <div class="span12">
                <div class="span5 control-group">
                    <label class="">Attention</label>
                    @Html.TextBoxFor(x => x.ShippingAddress.Attention, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="">Line 1</label>
                    @Html.TextBoxFor(x => x.ShippingAddress.Line1, new { @class = "span12" })
                </div>
            </div>
            <div class="span12">
                <div class="span5 control-group">
                    <label class="">Line 2</label>
                    @Html.TextBoxFor(x => x.ShippingAddress.Line2, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="">City</label>
                    @Html.TextBoxFor(x => x.ShippingAddress.City, new { @class = "span12" })
                </div>
            </div>
            <div class="span12">
                <div class="span5 control-group">
                    <label class="">Postal code</label>
                    @Html.TextBoxFor(x => x.ShippingAddress.PostalCode, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="">Country</label>
                    @Html.DropDownList("ShippingAddress.CountryId", Model.AvailableCountries, new { @class = "span12" })
                </div>
            </div>
            <div class="span12">
                <div class="span5 control-group">
                    <label class="">Phone</label>
                    @Html.TextBoxFor(x => x.ShippingAddress.PhoneNumber, new { @class = "span12" })
                </div>
                <div class="span5 control-group">
                    <label class="">Mobile phone</label>
                    @Html.TextBoxFor(x => x.ShippingAddress.MobilePhoneNumber, new { @class = "span12" })
                </div>
            </div>
        </div>
    </div>

    
    <div style="clear: both;">
        <a href="/cart" class="btn btn-small">Back to cart</a>

        <input type="submit" value="Continue to Shipping" class="btn btn-sm btn-arrow-right pull-right" />
    </div>
</form>

src/MyUCommerceApp.Website/Views/mc/Basket.cshtml
@using System.Web.Mvc.Html
@model MyUCommerceApp.Website.Models.PurchaseOrderViewModel
@{
    Layout = "Layout.cshtml";
}

<h1>Your basket</h1>

<form method="POST">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>SKU</th>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>Total</th>
                <th>Remove</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.OrderLines.Count; i++)
            {
                var line = Model.OrderLines[i];
                <tr>

                    @Html.HiddenFor(model => model.OrderLines[i].Sku)
                    @Html.HiddenFor(model => model.OrderLines[i].VariantSku)
                    @Html.HiddenFor(model => model.OrderLines[i].OrderLineId)

                    <td>@line.Sku - @line.VariantSku</td>
                    <td>@line.ProductName</td>
                    <td>@Html.TextBoxFor(model => model.OrderLines[i].Quantity)</td>
                    <td>@line.Total</td>
                    <td>
                        <button type="submit" value="@line.OrderLineId" name="RemoveOrderlineId">Remove</button>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">OrderTotal</td>
                <td>@Model.OrderTotal</td>
            </tr>
        </tfoot>
    </table>
    <input type="submit" value="Update basket" name="Update" />
</form>

<a href="/billing" class="btn btn-sm pull-right">Continue to billing information</a>

src/MyUCommerceApp.Website/Views/mc/Category.cshtml
@using System.Collections
@using System.Collections.Generic
@using System.Web.UI
@using MyUCommerceApp.Website.Models
@model MyUCommerceApp.Website.Models.CategoryViewModel
@{
    Layout = "Layout.cshtml";

}

<h1>@Model.Name</h1>

<span>@Html.Raw(Model.Description)</span>

@foreach (ProductViewModel product in Model.Products)
{
    <div>
        <span>@product.Name</span>
		@if (product.PriceCalculation != null && product.PriceCalculation.IsDiscounted)
		{
			<span style="text-decoration: line-through;">@product.PriceCalculation.ListPrice.Amount</span>
		}

		@if (product.PriceCalculation != null)
		{
			<span>@product.PriceCalculation.YourPrice.Amount</span>
		}
        <a href="@product.Url">More info</a>
    </div>
}

src/MyUCommerceApp.Website/Views/mc/Complete.cshtml
@using System.Web.Mvc.Html
@{
    Layout = "Layout.cshtml";
}

<h1>Your Order has been completed</h1>

src/MyUCommerceApp.Website/Views/mc/Frontpage.cshtml
@inherits System.Web.Mvc.WebViewPage
@{
    Layout = "Layout.cshtml";
}

<p>Hello Master class</p>

src/MyUCommerceApp.Website/Views/mc/Layout.cshtml
@inherits System.Web.Mvc.WebViewPage
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <link href="~/Bootstrap/bootstrap-3.3.6-dist/css/Styles.css" rel="stylesheet" />
        <link href="/css/ucommerce.bootstrap.css" rel="stylesheet">
        <link href="/css/ucommerce.bootstrap-responsive.css" rel="stylesheet">
        <link href="/css/ucommerce.masterclass.css" rel="stylesheet">
        
        <script src="~/Bootstrap/bootstrap-3.3.6-dist/js/jQuery.js"></script>
        <script src="/scripts/ucommerce.bootstrap.js"> </script>
        <script src="/scripts/uCommerce.jQuery.js"></script>
        <script src="/scripts/uCommerce.ServiceStack.js"></script>
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <div class="row-fluid">
                        <div class="nav-collapse">
                            <ul class="nav">
                                <li>
                                    <a class="home" href="/store">Home</a>
                                </li>
                            </ul>
                        </div>
                        <div class="nav-collapse pull-right">
                            <ul class="nav">
                                <li>
                                    <a href="/cart"><i class="icon-shopping-cart icon-white"></i> Basket</a>
                                </li>
                            </ul>
                        </div> 
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span3">
                    @{ Html.RenderAction("CategoryNavigation", "MasterClassPartialView"); }
                </div>
                <div class="span9">
                    @RenderBody()
                </div>
            </div>
        </div>
    </body>
</html>

src/MyUCommerceApp.Website/Views/mc/Payment.cshtml
@using System.Web.Mvc.Html
@model MyUCommerceApp.Website.Models.PaymentViewModel
@{
    Layout = "Layout.cshtml";
}

<form method="POST">
    <div class="row-fluid well">
        <legend>Available payment methods</legend>
        
        @foreach (var paymentMethod in Model.AvailablePaymentMethods)
        {
            <div>
                @if (paymentMethod.Selected)
                {
                    @Html.RadioButtonFor(x => x.SelectedPaymentMethodId, paymentMethod.Value, new { @checked = "checked" })
                    <span>@paymentMethod.Text</span>
                }
                else
                {
                    @Html.RadioButtonFor(x => x.SelectedPaymentMethodId, paymentMethod.Value)
                    <span>@paymentMethod.Text</span>
                }
            </div>
        }
    </div>

    <a href="/shipping" class="btn btn-small">Back to Shipping Method</a>

    <input type="submit" class="btn btn-sm btn-arrow-right pull-right" value="Continue to preview order" />
</form>

src/MyUCommerceApp.Website/Views/mc/Product.cshtml
@using System.Web.UI
@using UCommerce.Runtime
@using UCommerce.EntitiesV2
@using UCommerce.Extensions
@using UCommerce.Api
@model MyUCommerceApp.Website.Models.ProductViewModel
@{
    Layout = "Layout.cshtml";
}

<h1>@Model.Name</h1>

@if (Model.PriceCalculation != null)
{
	<h2>Your price: <span>@Model.PriceCalculation.YourPrice.Amount</span></h2>
}


<span>@Html.Raw(Model.LongDescription)</span>

<form method="POST">
    <input type="hidden" name="Sku" value="@Model.Sku" />
    <select name="VariantSku">
        @foreach (var variant in Model.Variants)
        {
            <option value="@variant.VariantSku">@variant.VariantSku</option>
        }
    </select>
    <input type="submit" value="Add To Basket" />
</form>

src/MyUCommerceApp.Website/Views/mc/Shipping.cshtml
@using System.Web.Mvc.Html
@model MyUCommerceApp.Website.Models.ShippingViewModel
@{
    Layout = "Layout.cshtml";
}

<form method="POST">
    <div class="well">
        <legend>Available shipping methods</legend>
        @foreach (var shippingMethod in Model.AvailableShippingMethods)
        {
            <div>
                @if (shippingMethod.Selected)
                {
                    @Html.RadioButtonFor(x => x.SelectedShippingMethodId, shippingMethod.Value, new { @checked = "checked" })
                    <span>@shippingMethod.Text</span>
                }
                else
                {
                    @Html.RadioButtonFor(x => x.SelectedShippingMethodId, shippingMethod.Value)
                    <span>@shippingMethod.Text</span>
                }
            </div>
        }
    </div>
    

    <a href="/billing" class="btn btn-small">Back to Address Details</a>

    <input type="submit" class="btn btn-sm btn-arrow-right pull-right" value="Continue to payment method" />

</form>

src/MyUCommerceApp.Website/Views/mc/preview.cshtml
@using System.Web.Caching
@using UCommerce
@using UCommerce.Api
@using UCommerce.EntitiesV2
@model MyUCommerceApp.Website.Models.PurchaseOrderViewModel
@{
    Layout = "Layout.cshtml";
}

<div class="row-fluid well">
    <div class="span6">
        <h3>Billing address</h3>
        <br>
        <address>
            <strong>
                @Model.BillingAddress.FirstName @Model.BillingAddress.LastName
            </strong>
            <br>
            @Model.BillingAddress.Line1 @Model.BillingAddress.Line2<br>
            @Model.BillingAddress.PostalCode 
            @Model.BillingAddress.City<br>
            @Country.Get(Model.BillingAddress.CountryId).Name<br>
            <br>
            <abbr title="Phone">P:</abbr>@Model.BillingAddress.PhoneNumber<br>
            <abbr title="Mobile">M:</abbr>@Model.BillingAddress.MobilePhoneNumber<br>
            <abbr title="Email">E:</abbr><a id="content_1_lnkBillingMail" href="mailto:morten@skjoldager.eu">@Model.BillingAddress.EmailAddress</a>
        </address>
    </div>

    <div class="span6">
        <h3>Shipping address</h3>
        <br>
        <address>
            <strong>
                @Model.ShippingAddress.FirstName @Model.ShippingAddress.LastName
            </strong>
            <br>
            @Model.ShippingAddress.Line1 @Model.ShippingAddress.Line2<br>
            @Model.ShippingAddress.PostalCode
            @Model.ShippingAddress.City<br>
            @Country.Get(Model.ShippingAddress.CountryId).Name<br>
            <br>
            <abbr title="Phone">P:</abbr>@Model.ShippingAddress.PhoneNumber<br>
            <abbr title="Mobile">M:</abbr>@Model.ShippingAddress.MobilePhoneNumber<br>
            <abbr title="Email">E:</abbr><a id="content_1_lnkBillingMail" href="mailto:morten@skjoldager.eu">@Model.ShippingAddress.EmailAddress</a>
        </address>
    </div>

</div>

<h3>Order details</h3>
<table class="orderPreview table table-striped table-hover">
    <thead>
        <tr>
            <th>Sku</th>
            <th>Product name</th>
            <th>Quantiy</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.OrderLines.Count; i++)
        {
            var line = Model.OrderLines[i];
            <tr>

                @Html.HiddenFor(model => model.OrderLines[i].Sku)
                @Html.HiddenFor(model => model.OrderLines[i].VariantSku)
                @Html.HiddenFor(model => model.OrderLines[i].OrderLineId)

                <td>@line.Sku - @line.VariantSku</td>
                <td>@line.ProductName</td>
                <td>@Model.OrderLines[i].Quantity</td>
                <td>@line.Total</td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td class="no-border" colspan="2"></td>
            <td style="width: 110px">Sub total</td>
            <td class="money">@Model.SubTotal</td>
        </tr>
        <tr>
            <td class="no-border" colspan="2"></td>
            <td>Tax total</td>
            <td class="money">@Model.TaxTotal</td>
        </tr>
        <tr>
            <td class="no-border" colspan="2"></td>
            <td>Discounts </td>
            <td class="money">@Model.DiscountTotal</td>
        </tr>
        <tr>
            <td class="no-border" colspan="2"></td>
            <td>Shipping total</td>
            <td class="money">@Model.ShippingTotal</td>
        </tr>
        <tr>
            <td class="no-border" colspan="2"></td>
            <td>Payment total</td>
            <td class="money">@Model.PaymentTotal</td>
        </tr>
        <tr>
            <td class="no-border" colspan="2"></td>
            <td>Order total</td>
            <td class="money">@Model.OrderTotal</td>
        </tr>
    </tfoot>
</table>


<form method="POST">
    <a href="/payment" class="btn btn-small">Back to Payment Method</a>

    <input type="hidden" name="checkout" value="true" />
    <input type="submit" class="btn btn-sm btn-arrow-right pull-right" value="Confirm and continue to payment" />
</form>